spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leadlucky
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        id:
          new_generator_mappings: false

server:
  port: 8082

security:
  jwt:
    token:
      secret-key: secretafyo
      expire-length: 360000000
