server:
  address: 0.0.0.0
  port: 8082
  tomcat:
    accesslog:
      enabled: true
      directory: /tmp/log
      pattern: "%a,%t,%m,%U"

token-expiration: 864_000_000 # 10 days
token-gen-secret: fj&F0f+=jfn2n2nf

signup-message: 'Welcome to Leadlucky. Please <a href="{verifyurl}">verify your email address</a>.'
signup-subject: 'Welcome to Leadlucky!'
email-address: localhost@test.com

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: localhost@test.com
    password:
    protocol: smtp
  data:
    mongodb:
      database: leadlucky
      username: ll-dev
      password: l0calmach1ne
      host: localhost