server:
  address: 0.0.0.0
  port: 8082
  tomcat:
    accesslog:
      enabled: true
      directory: access_logs

#security:
#  ignored:
#    - "*.bundle*"

token-expiration: 864_000_000 # 10 days
token-gen-secret: fj&F0f+=jfn2n2nf

signup-message: 'Welcome to Leadlucky. Please <a href="{verifyurl}">verify your email-address</a>.'
signup-subject: 'Welcome to Leadlucky!'
email-address: steven@stlcomputerservices.com

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/leadlucky
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        id:
          new_generator_mappings: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: steven@stlcomputerservices.com
    password: 
    protocol: smtp

